services:
  frontend:
    build:
      context: nanolims_app
      target: development
    ports:
      - 3002:3000
    stdin_open: true
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - AUTH_SECRET=${AUTH_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    networks:
      - mongo
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - mongo
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
networks:
  mongo: